"""Cache only selected official USD assets and their file dependencies.

Import after SimulationApp starts, so the bundled USD libraries are available.
"""
import hashlib
import json
from pathlib import Path
from urllib.parse import urljoin, urlparse
from urllib.request import urlopen

from pxr import Sdf, UsdUtils

SOURCE = "https://omniverse-content-production.s3-us-west-2.amazonaws.com/Assets/Isaac/4.5/Isaac/Props/YCB/"


def prepare_assets(project: Path, objects: list[dict]) -> dict[str, Path]:
    root = project / "assets" / "YCB"
    root.mkdir(parents=True, exist_ok=True)
    visited = set()
    manifest = []
    total_bytes = 0

    def fetch(url):
        nonlocal total_bytes
        if url in visited:
            return
        if not url.startswith(SOURCE):
            raise RuntimeError(f"Dependency outside the selected official YCB directory: {url}")
        visited.add(url)
        relative = url[len(SOURCE):]
        target = (root / relative).resolve()
        if not target.is_relative_to(root.resolve()):
            raise ValueError(f"Unsafe asset path: {relative}")
        target.parent.mkdir(parents=True, exist_ok=True)
        if not target.exists():
            print(f"[ASSET] Downloading {url}", flush=True)
            with urlopen(url, timeout=60) as response:
                data = response.read(100 * 1024 * 1024 + 1)
            if len(data) > 100 * 1024 * 1024:
                raise RuntimeError("Unexpected asset larger than 100 MiB; stopping.")
            total_bytes += len(data)
            if total_bytes > 500 * 1024 * 1024:
                raise RuntimeError("Unexpected YCB download larger than 500 MiB; stopping.")
            with target.open("xb") as stream:
                stream.write(data)
        manifest.append({"path": str(target.relative_to(project)), "source": url,
                         "bytes": target.stat().st_size,
                         "sha256": hashlib.sha256(target.read_bytes()).hexdigest()})
        if target.suffix.lower() in (".usd", ".usda", ".usdc"):
            layer = Sdf.Layer.FindOrOpen(str(target))
            if layer is None:
                raise RuntimeError(f"Cannot read USD: {target}")
            paths = []

            def collect(path):
                paths.append(path)
                return path

            UsdUtils.ModifyAssetPaths(layer, collect)
            for dependency in paths:
                # OmniPBR.mdl and similar names resolve through Kit's built-in MDL search path.
                if not dependency or (dependency.endswith(".mdl") and "/" not in dependency):
                    continue
                fetch(urljoin(url, dependency))

    result = {}
    for obj in objects:
        relative = f"Axis_Aligned_Physics/{obj['asset']}.usd"
        fetch(SOURCE + relative)
        result[obj["name"]] = root / relative
    # This manifest is generated by this project; original asset files remain untouched.
    (root / "manifest.json").write_text(json.dumps(manifest, indent=2) + "\n")
    return result
